name: "ewidencja"
volumes:
  db: {}
services:
  backend:
    image: "zz/ewidencja/backend:0.1.0"
    container_name: "ewidencja-backend"
    build: "./aplikacja webowa - praca inzynierska/aplikacja webowa - praca inzynierska/"
    ports:
      - "5000:80"
    volumes:
      - "db:/var/db"
  frontend:
    image: "zz/ewidencja/frontend:0.1.0"
    container_name: "ewidencja-frontend"
    build: "./frontend/"
    ports:
      - "4173:5173"
    depends_on:
      - "backend"